---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: ${NAMESPACE}
  labels:
    app: docs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docs
  minReadySeconds: 10
  revisionHistoryLimit: 10
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 5
  template:
    metadata:
      labels:
        app: docs
    spec:
      restartPolicy: Always
      containers:
        - name: docs
          image: "${IMAGE}"
          ports:
          - containerPort: 80
            name: http
          readinessProbe:
            httpGet:
              path: "/"
              port: 3000
            initialDelaySeconds: 1
          livenessProbe:
            httpGet:
              path: "/"
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: ${NAMESPACE}
  labels:
    app: docs
spec:
  selector:
    app: docs
  ports:
  - name: http
    port: 80
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docs
  namespace: ${NAMESPACE}
  labels:
    app: docs
    ssl: "true"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - ${INGRESS_HOSTNAME}
    secretName: docs-tls
  rules:
    - host: ${INGRESS_HOSTNAME}
      http:
        paths:
        - backend:
            serviceName: docs
            servicePort: 80
          path: /
